#!/usr/bin/env bash

set -e -x

env_name=$1
if [ "$env_name" == '' ]
then
    env_name=lite
fi

bosh create-release --force
bosh -e lite upload-release --rebase
bosh -e lite -d reference-nozzle deploy manifests/reference-nozzle.yml \
  -o manifests/ops-files/standalone-loggregator.yml \
  --vars-file ~/workspace/loggregator/vars.yml \
  -v reference-nozzle-destination=http://postprinter.bosh-lite.com \
  -v reference-nozzle-shard-id=reference-nozzle-id \
  --vars-store=vars.yml -n


